module Canonball
  # ED-SDK Error Code Masks
  @@EDS_ISSPECIFIC_MASK =                                 0
  @@EDS_COMPONENTID_MASK =                                0
  @@EDS_RESERVED_MASK =                                   16711680
  @@EDS_ERRORID_MASK =                                    65535
  # ED-SDK Base Component IDs
  @@EDS_CMP_ID_CLIENT_COMPONENTID =                       16777216
  @@EDS_CMP_ID_LLSDK_COMPONENTID =                        33554432
  @@EDS_CMP_ID_HLSDK_COMPONENTID =                        50331648
  # ED-SDK Functin Success Code
  @@EDS_ERR_OK =                                          0
  # Miscellaneous errors
  @@EDS_ERR_UNIMPLEMENTED =                               1
  @@EDS_ERR_INTERNAL_ERROR =                              2
  @@EDS_ERR_MEM_ALLOC_FAILED =                            3
  @@EDS_ERR_MEM_FREE_FAILED =                             4
  @@EDS_ERR_OPERATION_CANCELLED =                         5
  @@EDS_ERR_INCOMPATIBLE_VERSION =                        6
  @@EDS_ERR_NOT_SUPPORTED =                               7
  @@EDS_ERR_UNEXPECTED_EXCEPTION =                        8
  @@EDS_ERR_PROTECTION_VIOLATION =                        9
  @@EDS_ERR_MISSING_SUBCOMPONENT =                        10
  @@EDS_ERR_SELECTION_UNAVAILABLE =                       11
  # File errors
  @@EDS_ERR_FILE_IO_ERROR =                               32
  @@EDS_ERR_FILE_TOO_MANY_OPEN =                          33
  @@EDS_ERR_FILE_NOT_FOUND =                              34
  @@EDS_ERR_FILE_OPEN_ERROR =                             35
  @@EDS_ERR_FILE_CLOSE_ERROR =                            36
  @@EDS_ERR_FILE_SEEK_ERROR =                             37
  @@EDS_ERR_FILE_TELL_ERROR =                             38
  @@EDS_ERR_FILE_READ_ERROR =                             39
  @@EDS_ERR_FILE_WRITE_ERROR =                            40
  @@EDS_ERR_FILE_PERMISSION_ERROR =                       41
  @@EDS_ERR_FILE_DISK_FULL_ERROR =                        42
  @@EDS_ERR_FILE_ALREADY_EXISTS =                         43
  @@EDS_ERR_FILE_FORMAT_UNRECOGNIZED =                    44
  @@EDS_ERR_FILE_DATA_CORRUPT =                           45
  @@EDS_ERR_FILE_NAMING_NA =                              46
  # Directory errors
  @@EDS_ERR_DIR_NOT_FOUND =                               64
  @@EDS_ERR_DIR_IO_ERROR =                                65
  @@EDS_ERR_DIR_ENTRY_NOT_FOUND =                         66
  @@EDS_ERR_DIR_ENTRY_EXISTS =                            67
  @@EDS_ERR_DIR_NOT_EMPTY =                               68
  # Property errors
  @@EDS_ERR_PROPERTIES_UNAVAILABLE =                      80
  @@EDS_ERR_PROPERTIES_MISMATCH =                         81
  @@EDS_ERR_PROPERTIES_NOT_LOADED =                       83
  # Function Parameter errors
  @@EDS_ERR_INVALID_PARAMETER =                           96
  @@EDS_ERR_INVALID_HANDLE =                              97
  @@EDS_ERR_INVALID_POINTER =                             98
  @@EDS_ERR_INVALID_INDEX =                               99
  @@EDS_ERR_INVALID_LENGTH =                              100
  @@EDS_ERR_INVALID_FN_POINTER =                          101
  @@EDS_ERR_INVALID_SORT_FN =                             102
  # Device errors
  @@EDS_ERR_DEVICE_NOT_FOUND =                            128
  @@EDS_ERR_DEVICE_BUSY =                                 129
  @@EDS_ERR_DEVICE_INVALID =                              130
  @@EDS_ERR_DEVICE_EMERGENCY =                            131
  @@EDS_ERR_DEVICE_MEMORY_FULL =                          132
  @@EDS_ERR_DEVICE_INTERNAL_ERROR =                       133
  @@EDS_ERR_DEVICE_INVALID_PARAMETER =                    134
  @@EDS_ERR_DEVICE_NO_DISK =                              135
  @@EDS_ERR_DEVICE_DISK_ERROR =                           136
  @@EDS_ERR_DEVICE_CF_GATE_CHANGED =                      137
  @@EDS_ERR_DEVICE_DIAL_CHANGED =                         138
  @@EDS_ERR_DEVICE_NOT_INSTALLED =                        139
  @@EDS_ERR_DEVICE_STAY_AWAKE =                           140
  @@EDS_ERR_DEVICE_NOT_RELEASED =                         141
  # Stream errors
  @@EDS_ERR_STREAM_IO_ERROR =                             160
  @@EDS_ERR_STREAM_NOT_OPEN =                             161
  @@EDS_ERR_STREAM_ALREADY_OPEN =                         162
  @@EDS_ERR_STREAM_OPEN_ERROR =                           163
  @@EDS_ERR_STREAM_CLOSE_ERROR =                          164
  @@EDS_ERR_STREAM_SEEK_ERROR =                           165
  @@EDS_ERR_STREAM_TELL_ERROR =                           166
  @@EDS_ERR_STREAM_READ_ERROR =                           167
  @@EDS_ERR_STREAM_WRITE_ERROR =                          168
  @@EDS_ERR_STREAM_PERMISSION_ERROR =                     169
  @@EDS_ERR_STREAM_COULDNT_BEGIN_THREAD =                 170
  @@EDS_ERR_STREAM_BAD_OPTIONS =                          171
  @@EDS_ERR_STREAM_END_OF_STREAM =                        172
  # Communications errors
  @@EDS_ERR_COMM_PORT_IS_IN_USE =                         192
  @@EDS_ERR_COMM_DISCONNECTED =                           193
  @@EDS_ERR_COMM_DEVICE_INCOMPATIBLE =                    194
  @@EDS_ERR_COMM_BUFFER_FULL =                            195
  @@EDS_ERR_COMM_USB_BUS_ERR =                            196
  # Lock/Unlock
  @@EDS_ERR_USB_DEVICE_LOCK_ERROR =                       208
  @@EDS_ERR_USB_DEVICE_UNLOCK_ERROR =                     209
  # STI/WIA
  @@EDS_ERR_STI_UNKNOWN_ERROR =                           224
  @@EDS_ERR_STI_INTERNAL_ERROR =                          225
  @@EDS_ERR_STI_DEVICE_CREATE_ERROR =                     226
  @@EDS_ERR_STI_DEVICE_RELEASE_ERROR =                    227
  @@EDS_ERR_DEVICE_NOT_LAUNCHED =                         228
  @@EDS_ERR_ENUM_NA =                                     240
  @@EDS_ERR_INVALID_FN_CALL =                             241
  @@EDS_ERR_HANDLE_NOT_FOUND =                            242
  @@EDS_ERR_INVALID_ID =                                  243
  @@EDS_ERR_WAIT_TIMEOUT_ERROR =                          244
  # PTP
  @@EDS_ERR_SESSION_NOT_OPEN =                           8195
  @@EDS_ERR_INVALID_TRANSACTIONID =                      8196
  @@EDS_ERR_INCOMPLETE_TRANSFER =                        8199
  @@EDS_ERR_INVALID_STRAGEID =                           8200
  @@EDS_ERR_DEVICEPROP_NOT_SUPPORTED =                   8202
  @@EDS_ERR_INVALID_OBJECTFORMATCODE =                   8203
  @@EDS_ERR_SELF_TEST_FAILED =                           8209
  @@EDS_ERR_PARTIAL_DELETION =                           8210
  @@EDS_ERR_SPECIFICATION_BY_FORMAT_UNSUPPORTED =        8212
  @@EDS_ERR_NO_VALID_OBJECTINFO =                        8213
  @@EDS_ERR_INVALID_CODE_FORMAT =                        8214
  @@EDS_ERR_UNKNOWN_VENDOR_CODE =                        8215
  @@EDS_ERR_CAPTURE_ALREADY_TERMINATED =                 8216
  @@EDS_ERR_INVALID_PARENTOBJECT =                       8218
  @@EDS_ERR_INVALID_DEVICEPROP_FORMAT =                  8219
  @@EDS_ERR_INVALID_DEVICEPROP_VALUE =                   8220
  @@EDS_ERR_SESSION_ALREADY_OPEN =                       8222
  @@EDS_ERR_TRANSACTION_CANCELLED =                      8223
  @@EDS_ERR_SPECIFICATION_OF_DESTINATION_UNSUPPORTED =   8224
  @@EDS_ERR_NOT_CAMERA_SUPPORT_SDK_VERSION =             8225
  # PTP Vendor
  @@EDS_ERR_UNKNOWN_COMMAND =                            40961
  @@EDS_ERR_OPERATION_REFUSED =                          40965
  @@EDS_ERR_LENS_COVER_CLOSE =                           40966
  @@EDS_ERR_LOW_BATTERY =                                41217
  @@EDS_ERR_OBJECT_NOTREADY =                            41218
  @@EDS_ERR_CANNOT_MAKE_OBJECT =                         41220
  @@EDS_ERR_MEMORYSTATUS_NOTREADY =                      41222
  # Take Picture errors
  @@EDS_ERR_TAKE_PICTURE_AF_NG =                          36097
  @@EDS_ERR_TAKE_PICTURE_RESERVED =                       36098
  @@EDS_ERR_TAKE_PICTURE_MIRROR_UP_NG =                   36099
  @@EDS_ERR_TAKE_PICTURE_SENSOR_CLEANING_NG =             36100
  @@EDS_ERR_TAKE_PICTURE_SILENCE_NG =                     36101
  @@EDS_ERR_TAKE_PICTURE_NO_CARD_NG =                     36102
  @@EDS_ERR_TAKE_PICTURE_CARD_NG =                        36103
  @@EDS_ERR_TAKE_PICTURE_CARD_PROTECT_NG =                36104
  @@EDS_ERR_TAKE_PICTURE_MOVIE_CROP_NG =                  36105
  @@EDS_ERR_TAKE_PICTURE_STROBO_CHARGE_NG =               36106
  @@EDS_ERR_TAKE_PICTURE_NO_LENS_NG =                     36107
  @@EDS_ERR_TAKE_PICTURE_SPECIAL_MOVIE_MODE_NG =          36108
  @@EDS_ERR_TAKE_PICTURE_LV_REL_PROHIBIT_MODE_NG =        36109
  @@EDS_ERR_LAST_GENERIC_ERROR_PLUS_ONE =                 245
end
